// File d'attente des écritures hors ligne (lib/fileAttente.ts).
// node --experimental-strip-types app/scripts/verifier-file-attente.ts
import { verifie, bilan } from './_assert.ts'
import { aGarder, aMettreEnCache, avecIdentifiant, classerReponse, cibleDe, delaiPanneauDe, delaiReessai, estLectureEnFile, estPanneServeur, niveauAffichage, phraseBandeau, reponseGardee, resumeDe } from '../src/lib/fileAttente.ts'

const B = 'https://x.supabase.co'
console.log('ce qu’on garde')
verifie('ajout dans messages', aGarder('POST', `${B}/rest/v1/messages`))
verifie('modification de chantier', aGarder('PATCH', `${B}/rest/v1/chantiers?id=eq.1`))
verifie('suppression', aGarder('DELETE', `${B}/rest/v1/chantiers?id=in.(1,2)`))
verifie('RPC d’écriture (repondre_message)', aGarder('POST', `${B}/rest/v1/rpc/repondre_message`))
verifie('RPC de lecture : non', !aGarder('POST', `${B}/rest/v1/rpc/etat_renforts`) && !aGarder('POST', `${B}/rest/v1/rpc/moi`) && !aGarder('POST', `${B}/rest/v1/rpc/prochain_passage_chef`))
console.log('une LECTURE n’est jamais mise en file (régression PR #72 : « projets visibles {} » en attente)')
for (const n of ['projets_visibles', 'moi', 'etat_filet', 'journal_invites', 'invitations_du_projet', 'membres_detail', 'a_toi_a_revoir', 'prochain_passage_chef', 'reveiller_reportes', 'inviter', 'fonction_inconnue'])
  verifie(`${n} : pas gardée`, !aGarder('POST', `${B}/rest/v1/rpc/${n}`))
for (const n of ['repondre_message', 'certifier_chantier', 'corriger_chantier', 'regler_filet', 'mettre_de_cote', 'abandonner_chantier', 'signaler_ne_marche_pas', 'trancher_fusion', 'accepter_invitation'])
  verifie(`${n} : écriture gardée`, aGarder('POST', `${B}/rest/v1/rpc/${n}`))
verifie('projets_visibles : lecture mise en cache', aMettreEnCache('POST', `${B}/rest/v1/rpc/projets_visibles`))
verifie('inviter (jeton) : jamais en cache', !aMettreEnCache('POST', `${B}/rest/v1/rpc/inviter`))
console.log('migration de la file')
verifie('élément « projets_visibles » déjà en file : retiré', estLectureEnFile('POST', `${B}/rest/v1/rpc/projets_visibles`))
verifie('un GET en file : retiré', estLectureEnFile('GET', `${B}/rest/v1/messages`))
verifie('vraie écriture : conservée', !estLectureEnFile('POST', `${B}/rest/v1/messages`) && !estLectureEnFile('POST', `${B}/rest/v1/rpc/repondre_message`) && !estLectureEnFile('PATCH', `${B}/rest/v1/chantiers?id=eq.1`))
verifie('RPC inconnue déjà en file : conservée (jamais perdre une écriture)', !estLectureEnFile('POST', `${B}/rest/v1/rpc/fonction_inconnue`))
console.log('quand le panneau apparaît')
const base = { attente: 0, refuses: 0, horsLigne: false, plusAncienAttente: null as number | null, maintenant: 100_000, delaiS: 10 }
verifie('rien : rien', niveauAffichage(base) === 'rien')
verifie('coupure brève sans écriture : voyant seulement', niveauAffichage({ ...base, horsLigne: true }) === 'voyant')
verifie('écriture en attente depuis 3 s : voyant, pas de panneau', niveauAffichage({ ...base, attente: 1, horsLigne: true, plusAncienAttente: 97_000 }) === 'voyant')
verifie('écriture en attente depuis 10 s : panneau', niveauAffichage({ ...base, attente: 1, horsLigne: true, plusAncienAttente: 90_000 }) === 'panneau')
verifie('délai réglé à 60 s : toujours voyant à 30 s', niveauAffichage({ ...base, delaiS: 60, attente: 1, horsLigne: true, plusAncienAttente: 70_000 }) === 'voyant')
verifie('refus du serveur : panneau tout de suite', niveauAffichage({ ...base, refuses: 1 }) === 'panneau')
verifie('délai : défaut 10, valeur lue, valeur absurde ignorée', delaiPanneauDe(null) === 10 && delaiPanneauDe('30') === 30 && delaiPanneauDe('x') === 10 && delaiPanneauDe('-5') === 10)
verifie('RPC à secret (jeton) : jamais gardée', !aGarder('POST', `${B}/rest/v1/rpc/regler_reveil_immediat`))
verifie('abonnement push : non', !aGarder('POST', `${B}/rest/v1/push_abonnements`))
verifie('dépôt de fichier', aGarder('POST', `${B}/storage/v1/object/cockpit-medias/a/b.png`))
verifie('lecture : jamais gardée', !aGarder('GET', `${B}/rest/v1/messages`))
verifie('connexion (auth) : jamais gardée', !aGarder('POST', `${B}/auth/v1/token?grant_type=password`))
verifie('lecture de table mise en cache', aMettreEnCache('GET', `${B}/rest/v1/chantiers?select=*`) && !aMettreEnCache('POST', `${B}/rest/v1/chantiers`) && !aMettreEnCache('GET', `${B}/auth/v1/user`))
verifie('RPC de lecture (moi, etat_*) mise en cache, pas reveiller_reportes ni une écriture', aMettreEnCache('POST', `${B}/rest/v1/rpc/moi`) && aMettreEnCache('POST', `${B}/rest/v1/rpc/etat_renforts`) && !aMettreEnCache('POST', `${B}/rest/v1/rpc/reveiller_reportes`) && !aMettreEnCache('POST', `${B}/rest/v1/rpc/certifier_chantier`))
verifie('cible rpc', cibleDe(`${B}/rest/v1/rpc/abc?x=1`).nom === 'abc')

console.log('identifiant fixé avant le renvoi')
let n = 0
const gen = () => `id${++n}`
verifie('message sans id : id ajouté', JSON.parse(avecIdentifiant(`${B}/rest/v1/messages`, 'POST', '{"corps":"a"}', gen)!).id === 'id1')
verifie('id déjà là : inchangé', avecIdentifiant(`${B}/rest/v1/messages`, 'POST', '{"id":"z","corps":"a"}', gen) === '{"id":"z","corps":"a"}')
verifie('tableau : un id par ligne', JSON.parse(avecIdentifiant(`${B}/rest/v1/messages`, 'POST', '[{"a":1},{"a":2}]', gen)!).every((o: { id?: string }) => !!o.id))
verifie('autre table : inchangé', avecIdentifiant(`${B}/rest/v1/sections`, 'POST', '{"nom":"a"}', gen) === '{"nom":"a"}')
verifie('PATCH : inchangé', avecIdentifiant(`${B}/rest/v1/messages`, 'PATCH', '{"corps":"a"}', gen) === '{"corps":"a"}')
verifie('corps illisible : inchangé', avecIdentifiant(`${B}/rest/v1/messages`, 'POST', 'pas du json', gen) === 'pas du json')

console.log('réponses du serveur au renvoi')
verifie('200/201/204 : fait', classerReponse(200) === 'fait' && classerReponse(201) === 'fait' && classerReponse(204) === 'fait')
verifie('409 (déjà arrivé) : fait', classerReponse(409) === 'fait')
verifie('401, 429, 500, 503 : on réessaie', [401, 429, 500, 503].every((s) => classerReponse(s) === 'reessayer'))
verifie('400, 403, 404, 422 : refusé, gardé visible', [400, 403, 404, 422].every((s) => classerReponse(s) === 'refuse'))
verifie('502/503/504 en direct = panne ; 500 = vraie erreur', estPanneServeur(503) && !estPanneServeur(500))

console.log('réponse fabriquée')
verifie('rpc → null', reponseGardee('POST', `${B}/rest/v1/rpc/f`, '{}', '').corps === 'null')
verifie('insert minimal → 201 vide', reponseGardee('POST', `${B}/rest/v1/messages`, '{}', 'return=minimal').status === 201)
verifie('insert + representation → écho en tableau', reponseGardee('POST', `${B}/rest/v1/messages`, '{"a":1}', 'return=representation').corps === '[{"a":1}]')
verifie('patch → 204', reponseGardee('PATCH', `${B}/rest/v1/messages`, '{}', '').status === 204)

console.log('texte du bandeau')
verifie('rien à dire', phraseBandeau({ attente: 0, refuses: 0, horsLigne: false, envoi: false }) === null)
verifie('hors ligne seulement', phraseBandeau({ attente: 0, refuses: 0, horsLigne: true, envoi: false })?.texte.startsWith('Hors ligne') === true)
verifie('1 en attente (singulier)', /1 élément enregistré sur cet appareil/.test(phraseBandeau({ attente: 1, refuses: 0, horsLigne: false, envoi: false })!.texte))
verifie('3 en attente (pluriel)', /3 éléments enregistrés.*envoyés/.test(phraseBandeau({ attente: 3, refuses: 0, horsLigne: false, envoi: false })!.texte))
verifie('envoi en cours', /Envoi de 2 éléments/.test(phraseBandeau({ attente: 2, refuses: 0, horsLigne: false, envoi: true })!.texte))
verifie('refusé prime, niveau erreur', phraseBandeau({ attente: 2, refuses: 1, horsLigne: true, envoi: false })?.niveau === 'erreur')
verifie('résumé lisible', resumeDe('POST', `${B}/rest/v1/messages`) === 'Message dans un fil (ajout)' && resumeDe('POST', `${B}/rest/v1/rpc/certifier_chantier`).includes('certifier chantier'))
verifie('délai croissant plafonné', delaiReessai(1) === 30_000 && delaiReessai(2) === 60_000 && delaiReessai(20) === 15 * 60_000)
bilan('verifier-file-attente')
